# Input file to set runtime parameters

[Logfile]
  run_comment = "RT Instability"
  log_file = "INS_RT_Instability.log"

[Grid]
  geometry = "cartesian"
  xmin = 0.0
  xmax = 1.0
  ymin = 0.0
  ymax = 4.0
  xl_boundary_type = "slip_ins"
  xr_boundary_type = "slip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "noslip_ins"
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1.0e-13
  gr_amrexMG_max_iter = 200
  nblockx = 2
  nblocky = 8
  nrefs = 10000000
  lrefine_min = 1
  lrefine_max = 1
  flux_correct = true
  enableMaskedGCFill = true

[IncompNS]
  ins_invReynolds = 0.0285
  ins_gravY = -1.0
  ins_cflFlg = 0
  ins_cfl = 0.3
  ins_sigma = 0.2
  ins_dtSpec = 1.25e-5
  ins_pressureCorrect = false
  ins_intSchm = 2
  ins_advSchm = 2

[Simulation]
  sim_lengthScaleMeters = 1.0
  sim_timeScaleSeconds = 1.0

[Multiphase]
  mph_rhoGas = 0.001
  mph_muGas = 0.01
  mph_iPropSmear = 1.5
  mph_invWeber = 0.001

[Driver]
  restart = false
  nend = 1200000
  tmax = 80
  dtinit = 1.25e-5
  dtmax = 1.25e-5
  tstep_change_factor = 1.0
  wall_clock_time_limit = -1

[IO]
  basenm = "INS_RT_Instability_"
  checkpointFileIntervalTime = 1.0
  checkpointFileIntervalStep = 0
  plotFileIntervalTime = 0.1
  plotFileIntervalStep = 0
  checkpointFileNumber = 0
  rolling_checkpoint = 2
  plotFileNumber = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "dust"
  plot_var_6 = "rhoc"
  ignoreForcedPlot = true
